// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_EuRTcHNoQAyD8TAZvZ5YMLzjPCQbtpM',
    appId: '1:286750728795:web:74030d8c8cf21b9abc957e',
    messagingSenderId: '286750728795',
    projectId: 'chat-ca617',
    authDomain: 'chat-ca617.firebaseapp.com',
    storageBucket: 'chat-ca617.firebasestorage.app',
    measurementId: 'G-02FQ9PB1S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB18ONsS9FYjMIxf0tZws-jUf0L-EkcFDU',
    appId: '1:286750728795:android:e8f8acdf69c6a76fbc957e',
    messagingSenderId: '286750728795',
    projectId: 'chat-ca617',
    storageBucket: 'chat-ca617.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDibctFbCqPkK6oIB3nd4in2kq3_-2F4vI',
    appId: '1:286750728795:ios:f6d1900a891affb5bc957e',
    messagingSenderId: '286750728795',
    projectId: 'chat-ca617',
    storageBucket: 'chat-ca617.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDibctFbCqPkK6oIB3nd4in2kq3_-2F4vI',
    appId: '1:286750728795:ios:f6d1900a891affb5bc957e',
    messagingSenderId: '286750728795',
    projectId: 'chat-ca617',
    storageBucket: 'chat-ca617.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_EuRTcHNoQAyD8TAZvZ5YMLzjPCQbtpM',
    appId: '1:286750728795:web:65781fa46d4b99d3bc957e',
    messagingSenderId: '286750728795',
    projectId: 'chat-ca617',
    authDomain: 'chat-ca617.firebaseapp.com',
    storageBucket: 'chat-ca617.firebasestorage.app',
    measurementId: 'G-LF3GEKTL68',
  );
}
